name: Create draft release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version number without "v" tag prefix (i.e. "1.0.0")

jobs:
  draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: nlsfi/python-repo-draft-release-action@v1.0.1
        with:
          version: ${{ inputs.version }}
          version_file: pyproject.toml
